# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PipelineConfig.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PipelineConfig.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14PipelineConfig.proto\"-\n\x0eParameterValue\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\"V\n\x0eOperatorConfig\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tclasspath\x18\x02 \x01(\t\x12#\n\nparameters\x18\x03 \x03(\x0b\x32\x0f.ParameterValue\"@\n\rNamedOperator\x12\x0c\n\x04name\x18\x01 \x01(\t\x12!\n\x08operator\x18\x02 \x01(\x0b\x32\x0f.OperatorConfig\"3\n\x0ePipelineConfig\x12!\n\toperators\x18\x01 \x03(\x0b\x32\x0e.NamedOperatorb\x06proto3')
)




_PARAMETERVALUE = _descriptor.Descriptor(
  name='ParameterValue',
  full_name='ParameterValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ParameterValue.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='ParameterValue.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=69,
)


_OPERATORCONFIG = _descriptor.Descriptor(
  name='OperatorConfig',
  full_name='OperatorConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='OperatorConfig.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='classpath', full_name='OperatorConfig.classpath', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parameters', full_name='OperatorConfig.parameters', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=157,
)


_NAMEDOPERATOR = _descriptor.Descriptor(
  name='NamedOperator',
  full_name='NamedOperator',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='NamedOperator.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='operator', full_name='NamedOperator.operator', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=223,
)


_PIPELINECONFIG = _descriptor.Descriptor(
  name='PipelineConfig',
  full_name='PipelineConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='operators', full_name='PipelineConfig.operators', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=276,
)

_OPERATORCONFIG.fields_by_name['parameters'].message_type = _PARAMETERVALUE
_NAMEDOPERATOR.fields_by_name['operator'].message_type = _OPERATORCONFIG
_PIPELINECONFIG.fields_by_name['operators'].message_type = _NAMEDOPERATOR
DESCRIPTOR.message_types_by_name['ParameterValue'] = _PARAMETERVALUE
DESCRIPTOR.message_types_by_name['OperatorConfig'] = _OPERATORCONFIG
DESCRIPTOR.message_types_by_name['NamedOperator'] = _NAMEDOPERATOR
DESCRIPTOR.message_types_by_name['PipelineConfig'] = _PIPELINECONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ParameterValue = _reflection.GeneratedProtocolMessageType('ParameterValue', (_message.Message,), dict(
  DESCRIPTOR = _PARAMETERVALUE,
  __module__ = 'PipelineConfig_pb2'
  # @@protoc_insertion_point(class_scope:ParameterValue)
  ))
_sym_db.RegisterMessage(ParameterValue)

OperatorConfig = _reflection.GeneratedProtocolMessageType('OperatorConfig', (_message.Message,), dict(
  DESCRIPTOR = _OPERATORCONFIG,
  __module__ = 'PipelineConfig_pb2'
  # @@protoc_insertion_point(class_scope:OperatorConfig)
  ))
_sym_db.RegisterMessage(OperatorConfig)

NamedOperator = _reflection.GeneratedProtocolMessageType('NamedOperator', (_message.Message,), dict(
  DESCRIPTOR = _NAMEDOPERATOR,
  __module__ = 'PipelineConfig_pb2'
  # @@protoc_insertion_point(class_scope:NamedOperator)
  ))
_sym_db.RegisterMessage(NamedOperator)

PipelineConfig = _reflection.GeneratedProtocolMessageType('PipelineConfig', (_message.Message,), dict(
  DESCRIPTOR = _PIPELINECONFIG,
  __module__ = 'PipelineConfig_pb2'
  # @@protoc_insertion_point(class_scope:PipelineConfig)
  ))
_sym_db.RegisterMessage(PipelineConfig)


# @@protoc_insertion_point(module_scope)
