version: 0.0

pipeline:
  - name: Blur1
    config:
      implementation: ezcv.operator.implementations.blur.GaussianBlur
      params:
        kernel_size: 3
        sigma: 1.5
  - name: Blur2
    config:
      implementation: ezcv.operator.implementations.blur.GaussianBlur
      params:
        kernel_size: 5
        sigma: 1